#!/bin/bash

# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
# (default: not set).
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Show the ~/Library folder (default: hidden).
chflags nohidden ~/Library

# Disable the warning when changing a file extension (default: true).
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Show remaining battery time, hide percentage.
# defaults write com.apple.menuextra.battery ShowPercent -string "NO"
defaults write com.apple.menuextra.battery ShowTime -string "YES"

# Show indicator lights for open applications in the Dock (default: false).
defaults write com.apple.dock show-process-indicators -bool true

# Enable Trackpad tap to click (default: false).
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad \
  Clicking -bool true

# Map bottom right Trackpad corner to right-click.
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad \
  TrackpadCornerSecondaryClick -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad \
  TrackpadRightClick -bool true

# Avoid creating .DS_Store files on network volumes (default: false).
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Kill affected applications
for app in Safari Finder Dock Mail SystemUIServer; do
  killall "$app" >/dev/null 2>&1;
done